/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;


import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.border.Border;
import javax.swing.plaf.basic.BasicBorders;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hamle
 */
public class FormU_Tienda extends javax.swing.JPanel {
    DefaultTableModel modelo;
    String texto = "";
    int totalcompra =0;
    
   //Crea la tabla y pone los dtos de un txt a la tabla 
    public FormU_Tienda() {
        initComponents();
        tabledark.fixTable(jScrollPane4);
        modelo = new DefaultTableModel();
        modelo.addColumn("Producto");
        modelo.addColumn("ID");
        modelo.addColumn("Precio");
        this.tabledark.setModel(modelo);
        
        String filePath = "src/Archivos/DatosTabla.txt";
        File file = new File(filePath);
        
        try {
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
            
            DefaultTableModel model = (DefaultTableModel)tabledark.getModel();
            Object[] lines = br.lines().toArray();
            
            for(int i = 0; i < lines.length; i++){
                String[] row = lines[i].toString().split(",");
                model.addRow(row);
            }
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Form_TablaPro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new com.raven.swing.PanelBorder();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabledark = new com.raven.swing.Table();
        jLabel1 = new javax.swing.JLabel();
        txfpro = new com.raven.swing.TextFild();
        txfprecio = new com.raven.swing.TextFild();
        txfid = new com.raven.swing.TextFild();
        txfcan = new com.raven.swing.TextFild();
        btAgregar = new Botones.MiBoton();
        btComprar = new Botones.MiBoton();
        panelBorder2 = new com.raven.swing.PanelBorder();
        textAreaScroll1 = new com.raven.swing.TextAreaScroll();
        txCarro = new com.raven.swing.TextArea();
        imageAvatar1 = new com.raven.swing.ImageAvatar();
        imageAvatar2 = new com.raven.swing.ImageAvatar();

        setOpaque(false);

        tabledark.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabledark.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabledarkMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tabledark);

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(135, 135, 135));
        jLabel1.setText("Lista de Productos");

        txfpro.setEditable(false);
        txfpro.setLabelText("Producto");
        txfpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfproActionPerformed(evt);
            }
        });

        txfprecio.setEditable(false);
        txfprecio.setLabelText("Precio\n");

        txfid.setEditable(false);
        txfid.setLabelText("ID\n");

        txfcan.setLabelText("Cantidad\n");
        txfcan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfcanActionPerformed(evt);
            }
        });

        btAgregar.setText("Agregar");
        btAgregar.setBorderColor(new java.awt.Color(33, 147, 176));
        btAgregar.setColorClick(new java.awt.Color(51, 102, 255));
        btAgregar.setColorover(new java.awt.Color(109, 213, 237));
        btAgregar.setRadius(30);
        btAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarActionPerformed(evt);
            }
        });

        btComprar.setBackground(new java.awt.Color(255, 255, 255));
        btComprar.setText("Comprar");
        btComprar.setBorderColor(new java.awt.Color(33, 147, 176));
        btComprar.setColorClick(new java.awt.Color(51, 102, 255));
        btComprar.setColorover(new java.awt.Color(109, 213, 237));
        btComprar.setRadius(30);
        btComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComprarActionPerformed(evt);
            }
        });

        panelBorder2.setBackground(new java.awt.Color(255, 255, 255));

        textAreaScroll1.setLabelText("Carro de Compras");

        txCarro.setEditable(false);
        txCarro.setBackground(new java.awt.Color(255, 255, 255));
        txCarro.setColumns(20);
        txCarro.setRows(5);
        textAreaScroll1.setViewportView(txCarro);

        javax.swing.GroupLayout panelBorder2Layout = new javax.swing.GroupLayout(panelBorder2);
        panelBorder2.setLayout(panelBorder2Layout);
        panelBorder2Layout.setHorizontalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textAreaScroll1, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBorder2Layout.setVerticalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textAreaScroll1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addContainerGap())
        );

        imageAvatar1.setGradientColor1(new java.awt.Color(33, 147, 176));
        imageAvatar1.setGradientColor2(new java.awt.Color(109, 213, 237));
        imageAvatar1.setImage(new javax.swing.ImageIcon(getClass().getResource("/com/raven/image/Granola Almendras y semilla.jpg"))); // NOI18N

        imageAvatar2.setGradientColor1(new java.awt.Color(33, 147, 176));
        imageAvatar2.setGradientColor2(new java.awt.Color(109, 213, 237));
        imageAvatar2.setImage(new javax.swing.ImageIcon(getClass().getResource("/com/raven/image/Granola Coco.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelBorder2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(btAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(btComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txfpro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txfprecio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txfid, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfcan, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imageAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imageAvatar2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageAvatar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfpro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfcan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 46, Short.MAX_VALUE))
                    .addComponent(imageAvatar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelBorder2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txfproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfproActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfproActionPerformed

    private void txfcanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfcanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfcanActionPerformed
    //eso lo que hace es que pone lo quie esta en la tabla en txtfild
    private void tabledarkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabledarkMouseClicked
        int seleccionar= tabledark.rowAtPoint(evt.getPoint());
        txfpro.setText(String.valueOf(tabledark.getValueAt(seleccionar, 0)));
        txfid.setText(String.valueOf(tabledark.getValueAt(seleccionar, 1)));
        txfprecio.setText(String.valueOf(tabledark.getValueAt(seleccionar, 2)));
    }//GEN-LAST:event_tabledarkMouseClicked
    //agrega lo que este en los textfild a el carro de compras
    private void btAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarActionPerformed
        
        int total =0;
        
        int cantidad1 = Integer.parseInt(txfcan.getText());
        int precio1 = Integer.parseInt(txfprecio.getText());
        
        if(txfcan.getText() != " "&&txfprecio.getText() != " "){
            total = precio1 *cantidad1;
           
        }
        txCarro.setText("");
        
        totalcompra+=total; 
        txCarro.setText("");
        texto += txfpro.getText() + "\t" + txfid.getText() + "\t" + txfprecio.getText() + "\t" + total + "\n";
        
        txCarro.setText(texto);
        txfpro.setText("");
        txfid.setText("");
        txfprecio.setText("");
        txfcan.setText(""); 
        
        
    }//GEN-LAST:event_btAgregarActionPerformed
    
    // da el total de lña compra en el carro de comporas
    private void btComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComprarActionPerformed
        /*JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        Mensaje me = new Mensaje(frame, true);
        
        me.showAlert();*/
        texto=("");
        txCarro.setText("");
        JOptionPane.showMessageDialog(null, totalcompra);
        txCarro.setText("");
        totalcompra=0;
        txCarro.setText("");
        
        
        
        
    }//GEN-LAST:event_btComprarActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Botones.MiBoton btAgregar;
    private Botones.MiBoton btComprar;
    private com.raven.swing.ImageAvatar imageAvatar1;
    private com.raven.swing.ImageAvatar imageAvatar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane4;
    private com.raven.swing.PanelBorder panelBorder1;
    private com.raven.swing.PanelBorder panelBorder2;
    private com.raven.swing.Table tabledark;
    private com.raven.swing.TextAreaScroll textAreaScroll1;
    private com.raven.swing.TextArea txCarro;
    private com.raven.swing.TextFild txfcan;
    private com.raven.swing.TextFild txfid;
    private com.raven.swing.TextFild txfprecio;
    private com.raven.swing.TextFild txfpro;
    // End of variables declaration//GEN-END:variables
}
