/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import java.awt.List;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hamle
 */
public class Form_TablaPro extends javax.swing.JPanel {
    DefaultTableModel modelo;
    private static Scanner sc;

    //crea una tabla y pone los datos de un txt  a la tabla
    public Form_TablaPro() {
        initComponents();
        tablaProm.fixTable(jScrollPane2);
        modelo = new DefaultTableModel();
        modelo.addColumn("Producto");
        modelo.addColumn("ID");
        modelo.addColumn("Precio");
        this.tablaProm.setModel(modelo);
        
        String filePath = "src/Archivos/DatosTabla.txt";
        File file = new File(filePath);
        
        try {
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
            
            DefaultTableModel model = (DefaultTableModel)tablaProm.getModel();
            Object[] lines = br.lines().toArray();
            
            for(int i = 0; i < lines.length; i++){
                String[] row = lines[i].toString().split(",");
                model.addRow(row);
            }
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Form_TablaPro.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder3 = new com.raven.swing.PanelBorder();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProm = new com.raven.swing.Table();
        jLabel1 = new javax.swing.JLabel();
        txtPro = new com.raven.swing.TextFild();
        txtId = new com.raven.swing.TextFild();
        txtNuev = new com.raven.swing.TextFild();
        jLabel2 = new javax.swing.JLabel();
        txtCol = new com.raven.swing.TextFild();
        imageAvatar1 = new com.raven.swing.ImageAvatar();
        miBoton1 = new Botones.MiBoton();
        miBoton2 = new Botones.MiBoton();
        txtFil = new com.raven.swing.TextFild();
        txtPre = new com.raven.swing.TextFild();
        btModificar = new Botones.MiBoton();
        btElimarT = new Botones.MiBoton();
        btGuardar = new Botones.MiBoton();

        setOpaque(false);

        tablaProm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaProm);

        javax.swing.GroupLayout panelBorder3Layout = new javax.swing.GroupLayout(panelBorder3);
        panelBorder3.setLayout(panelBorder3Layout);
        panelBorder3Layout.setHorizontalGroup(
            panelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        panelBorder3Layout.setVerticalGroup(
            panelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(127, 127, 127));
        jLabel1.setText("Productos");

        txtPro.setLabelText("Producto");
        txtPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProActionPerformed(evt);
            }
        });

        txtId.setLabelText("ID");

        txtNuev.setLabelText("Nuevo Dato");
        txtNuev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNuevActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(127, 127, 127));
        jLabel2.setText("Modificar");

        txtCol.setLabelText("Columna");
        txtCol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColActionPerformed(evt);
            }
        });

        imageAvatar1.setGradientColor1(new java.awt.Color(33, 147, 176));
        imageAvatar1.setGradientColor2(new java.awt.Color(109, 213, 237));
        imageAvatar1.setImage(new javax.swing.ImageIcon(getClass().getResource("/com/raven/image/arreglar.jpg"))); // NOI18N

        miBoton1.setText("Agregar");
        miBoton1.setBorderColor(new java.awt.Color(33, 147, 176));
        miBoton1.setColorClick(new java.awt.Color(51, 102, 255));
        miBoton1.setColorover(new java.awt.Color(109, 213, 237));
        miBoton1.setRadius(30);
        miBoton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBoton1ActionPerformed(evt);
            }
        });

        miBoton2.setText("Eliminar");
        miBoton2.setBorderColor(new java.awt.Color(33, 147, 176));
        miBoton2.setColorClick(new java.awt.Color(51, 102, 255));
        miBoton2.setColorover(new java.awt.Color(109, 213, 237));
        miBoton2.setRadius(30);
        miBoton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBoton2ActionPerformed(evt);
            }
        });

        txtFil.setLabelText("Fila");
        txtFil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFilActionPerformed(evt);
            }
        });

        txtPre.setLabelText("Precio");

        btModificar.setText("Modificar");
        btModificar.setBorderColor(new java.awt.Color(33, 147, 176));
        btModificar.setColorClick(new java.awt.Color(51, 102, 255));
        btModificar.setColorover(new java.awt.Color(109, 213, 237));
        btModificar.setRadius(30);
        btModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModificarActionPerformed(evt);
            }
        });

        btElimarT.setText("Elimiar Todo");
        btElimarT.setBorderColor(new java.awt.Color(33, 147, 176));
        btElimarT.setColorClick(new java.awt.Color(51, 102, 255));
        btElimarT.setColorover(new java.awt.Color(109, 213, 237));
        btElimarT.setRadius(30);
        btElimarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btElimarTActionPerformed(evt);
            }
        });

        btGuardar.setText("Guardar");
        btGuardar.setBorderColor(new java.awt.Color(33, 147, 176));
        btGuardar.setColorClick(new java.awt.Color(51, 102, 255));
        btGuardar.setColorover(new java.awt.Color(109, 213, 237));
        btGuardar.setRadius(30);
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelBorder3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(miBoton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(miBoton2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(209, 209, 209)
                                .addComponent(btGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(txtPre, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(txtPro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                .addComponent(imageAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btElimarT, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCol, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFil, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNuev, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 21, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(miBoton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(miBoton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNuev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btElimarT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(imageAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addComponent(panelBorder3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void miBoton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBoton1ActionPerformed
        String []info = new String[3];
        info[0] = txtPro.getText();
        info[1] = txtId.getText();
        info[2] = txtPre.getText();
        modelo.addRow(info);
        
        txtPro.setText("");
        txtId.setText("");
        txtPre.setText("");
        txtNuev.setText("");
    }//GEN-LAST:event_miBoton1ActionPerformed

    private void miBoton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBoton2ActionPerformed
        int fila= tablaProm.getSelectedRow();
        if (fila >= 0){
            modelo.removeRow(fila);
        }else{
            JOptionPane.showMessageDialog(null, "Seleccionar Fila");
        }
    }//GEN-LAST:event_miBoton2ActionPerformed

    private void txtColActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColActionPerformed

    private void txtFilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFilActionPerformed

    private void txtProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProActionPerformed

    private void btModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModificarActionPerformed
        int fila= Integer.parseInt(txtFil.getText());
        int columna = Integer.parseInt(txtCol.getText());
        modelo.setValueAt(txtNuev.getText(), fila, columna);
    }//GEN-LAST:event_btModificarActionPerformed

    private void btElimarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btElimarTActionPerformed
        int fila= tablaProm.getRowCount();
        for(int i = fila-1; i >=0; i--){
            modelo.removeRow(i);
        }
    }//GEN-LAST:event_btElimarTActionPerformed

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        guardaTabla();
    }//GEN-LAST:event_btGuardarActionPerformed

    private void txtNuevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNuevActionPerformed
    
   private void guardaTabla(){
        String filePath = "src/Archivos/DatosTabla.txt";
        File file = new File(filePath);
        try {
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);
            
            for(int i = 0; i < tablaProm.getRowCount(); i++){//rows
                for(int j = 0; j < tablaProm.getColumnCount(); j++){//columns
                    bw.write(tablaProm.getValueAt(i, j).toString()+",");
                }
                bw.newLine();
            }
            
            bw.close();
            fw.close();
            
        } catch (IOException ex) {
            Logger.getLogger(Form_TablaPro.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
        
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Botones.MiBoton btElimarT;
    private Botones.MiBoton btGuardar;
    private Botones.MiBoton btModificar;
    private com.raven.swing.ImageAvatar imageAvatar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private Botones.MiBoton miBoton1;
    private Botones.MiBoton miBoton2;
    private com.raven.swing.PanelBorder panelBorder3;
    private com.raven.swing.Table tablaProm;
    private com.raven.swing.TextFild txtCol;
    private com.raven.swing.TextFild txtFil;
    private com.raven.swing.TextFild txtId;
    private com.raven.swing.TextFild txtNuev;
    private com.raven.swing.TextFild txtPre;
    private com.raven.swing.TextFild txtPro;
    // End of variables declaration//GEN-END:variables
}
