/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hamle
 */
public class Form_Provedores extends javax.swing.JPanel {
    DefaultTableModel modelo;
    private static Scanner sc;


    //crea una tabla y pone los datos de un txt  a la tabla
    public Form_Provedores() {
        initComponents();
        tablaProm.fixTable(jscroltable);
        modelo = new DefaultTableModel();
        modelo.addColumn("Proveedor");
        modelo.addColumn("Producto");
        
        modelo.addColumn("Precio");
        modelo.addColumn("Cantidad");
        this.tablaProm.setModel(modelo);
        String filePath = "src/Archivos/DatosTablaProve.txt";
        File file = new File(filePath);
        try {
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
            
            DefaultTableModel model = (DefaultTableModel)tablaProm.getModel();
            Object[] lines = br.lines().toArray();
            
            for(int i = 0; i < lines.length; i++){
                String[] row = lines[i].toString().split(",");
                model.addRow(row);
            }
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Form_TablaPro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtPro = new com.raven.swing.TextFild();
        txtProe = new com.raven.swing.TextFild();
        txtProducto = new com.raven.swing.TextFild();
        txtCan = new com.raven.swing.TextFild();
        agregar = new Botones.MiBoton();
        eliminar = new Botones.MiBoton();
        mbElimiarTodo = new Botones.MiBoton();
        modificar = new Botones.MiBoton();
        jLabel3 = new javax.swing.JLabel();
        txtFil = new com.raven.swing.TextFild();
        txtNuev = new com.raven.swing.TextFild();
        txtCol = new com.raven.swing.TextFild();
        mbGuardar = new Botones.MiBoton();
        imageAvatar1 = new com.raven.swing.ImageAvatar();
        panelBorder1 = new com.raven.swing.PanelBorder();
        jscroltable = new javax.swing.JScrollPane();
        tablaProm = new com.raven.swing.Table();

        setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(127, 127, 127));
        jLabel2.setText("Proveedores");

        txtPro.setLabelText("Proveedor");

        txtProe.setLabelText("Precio");
        txtProe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProeActionPerformed(evt);
            }
        });

        txtProducto.setLabelText("Producto");

        txtCan.setLabelText("Cantidad");
        txtCan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCanActionPerformed(evt);
            }
        });

        agregar.setText("Agregar");
        agregar.setBorderColor(new java.awt.Color(33, 147, 176));
        agregar.setColorClick(new java.awt.Color(51, 102, 255));
        agregar.setColorover(new java.awt.Color(109, 213, 237));
        agregar.setRadius(30);
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        eliminar.setText("Eliminar");
        eliminar.setBorderColor(new java.awt.Color(33, 147, 176));
        eliminar.setColorClick(new java.awt.Color(51, 102, 255));
        eliminar.setColorover(new java.awt.Color(109, 213, 237));
        eliminar.setRadius(30);
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        mbElimiarTodo.setText("Eliminar Todo");
        mbElimiarTodo.setBorderColor(new java.awt.Color(33, 147, 176));
        mbElimiarTodo.setColorClick(new java.awt.Color(51, 102, 255));
        mbElimiarTodo.setColorover(new java.awt.Color(109, 213, 237));
        mbElimiarTodo.setRadius(30);
        mbElimiarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbElimiarTodoActionPerformed(evt);
            }
        });

        modificar.setText("Modificar");
        modificar.setBorderColor(new java.awt.Color(33, 147, 176));
        modificar.setColorClick(new java.awt.Color(51, 102, 255));
        modificar.setColorover(new java.awt.Color(109, 213, 237));
        modificar.setRadius(30);
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(127, 127, 127));
        jLabel3.setText("Modificar");

        txtFil.setLabelText("Fila");

        txtNuev.setLabelText("Nuevo Dato");
        txtNuev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNuevActionPerformed(evt);
            }
        });

        txtCol.setLabelText("Columna");

        mbGuardar.setText("Guardar");
        mbGuardar.setBorderColor(new java.awt.Color(33, 147, 176));
        mbGuardar.setColorClick(new java.awt.Color(51, 102, 255));
        mbGuardar.setColorover(new java.awt.Color(109, 213, 237));
        mbGuardar.setRadius(30);
        mbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbGuardarActionPerformed(evt);
            }
        });

        imageAvatar1.setGradientColor1(new java.awt.Color(33, 147, 176));
        imageAvatar1.setGradientColor2(new java.awt.Color(109, 213, 237));
        imageAvatar1.setImage(new javax.swing.ImageIcon(getClass().getResource("/com/raven/image/provedoreshd.jpg"))); // NOI18N

        tablaProm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jscroltable.setViewportView(tablaProm);

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jscroltable, javax.swing.GroupLayout.DEFAULT_SIZE, 931, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jscroltable, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNuev, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(mbGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtFil, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtProe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPro, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCol, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(mbElimiarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imageAvatar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mbElimiarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNuev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mbGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(imageAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtProeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProeActionPerformed

    private void txtCanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCanActionPerformed
    //agrega la informacion de los textfil a la tabla
    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        String []info = new String[4];
        info[0] = txtPro.getText();
        info[1] = txtProducto.getText();
        info[2] = txtProe.getText();
        info[3] = txtCan.getText();
        modelo.addRow(info);

        txtProe.setText("");
        txtPro.setText("");
        txtProducto.setText("");
        txtCan.setText("");
    }//GEN-LAST:event_agregarActionPerformed
    // elimina la fila escojida en la tabla
    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        int fila= tablaProm.getSelectedRow();
        if (fila >= 0){
            modelo.removeRow(fila);
        }else{
            JOptionPane.showMessageDialog(null, "Seleccionar Fila");
        }
    }//GEN-LAST:event_eliminarActionPerformed
    //elimina toda la informacion de la tabla
    private void mbElimiarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbElimiarTodoActionPerformed
        int fila= tablaProm.getRowCount();
        for(int i = fila-1; i >=0; i--){
            modelo.removeRow(i);
        }
    }//GEN-LAST:event_mbElimiarTodoActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        int fila = Integer.parseInt(txtFil.getText());
        int columna = Integer.parseInt(txtCol.getText());
        modelo.setValueAt(txtNuev.getText(), fila, columna);
    }//GEN-LAST:event_modificarActionPerformed

    private void txtNuevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNuevActionPerformed
    
    private void mbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbGuardarActionPerformed
        guardaTabla();
    }//GEN-LAST:event_mbGuardarActionPerformed
   //guarda la informacion de la tabla
    private void guardaTabla(){
        String filePath = "src/Archivos/DatosTablaProve.txt";
        File file = new File(filePath);
        try {
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);
            
            for(int i = 0; i < tablaProm.getRowCount(); i++){//rows
                for(int j = 0; j < tablaProm.getColumnCount(); j++){//columns
                    bw.write(tablaProm.getValueAt(i, j).toString()+",");
                }
                bw.newLine();
            }
            
            bw.close();
            fw.close();
            
        } catch (IOException ex) {
            Logger.getLogger(Form_TablaPro.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Botones.MiBoton agregar;
    private Botones.MiBoton eliminar;
    private com.raven.swing.ImageAvatar imageAvatar1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jscroltable;
    private Botones.MiBoton mbElimiarTodo;
    private Botones.MiBoton mbGuardar;
    private Botones.MiBoton modificar;
    private com.raven.swing.PanelBorder panelBorder1;
    private com.raven.swing.Table tablaProm;
    private com.raven.swing.TextFild txtCan;
    private com.raven.swing.TextFild txtCol;
    private com.raven.swing.TextFild txtFil;
    private com.raven.swing.TextFild txtNuev;
    private com.raven.swing.TextFild txtPro;
    private com.raven.swing.TextFild txtProducto;
    private com.raven.swing.TextFild txtProe;
    // End of variables declaration//GEN-END:variables
}
