/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import com.raven.evento.EventItem;
import com.raven.model.Model_Item;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Point;
import javax.swing.ImageIcon;
import org.jdesktop.animation.timing.Animator;
import org.jdesktop.animation.timing.TimingTargetAdapter;
import org.jdesktop.animation.timing.interpolation.PropertySetter;

/**
 *
 * @author mpira
 */
public class MainVendedores extends javax.swing.JPanel {
    private Form_Vendedores home;
    private Animator animator;
    private Point animatePoint;
    private Model_Item itemSelected;

    /**
     * Creates new form MainVendedores
     */
    public MainVendedores() {
        initComponents();
        setBackground(new Color(0,0,0,0));
        
        init();
        animator= PropertySetter.createAnimator(500,mainPanel,"ImageLocation",animatePoint,mainPanel.getTargetLocation());
        animator.addTarget(new PropertySetter(mainPanel, "imageSize", new Dimension(130, 109), mainPanel.getTargetSize()));
        animator.setResolution(0);
        animator.setAcceleration(.5f);
        
        
    }
    private void init() {
        home = new Form_Vendedores();
        mainPanel.setLayout(new BorderLayout());
        mainPanel.add(home);
        testData();
        
        
    }
    private void testData() {
        home.setEvent(new EventItem() {
            @Override
            public void itemClick(Component com, Model_Item item) {
                if(itemSelected!=item){
                    if(!animator.isRunning()){
                        itemSelected=item;
                        animatePoint=getLocationOf(com);
                        mainPanel.setImage(item.getImage());
                        mainPanel.setImageLocation(animatePoint);
                        mainPanel.setImageSize(new Dimension(130,109));
                        mainPanel.repaint();
                        home.setSelected(com);
                        home.showItem(item);
                        animator.start();
                        
                    }
                }
                
                home.setSelected(com);
                home.showItem(item);
                
                
            }
            
        });
        
        home.addItem(new Model_Item("Hamlet", "Sistemas", new ImageIcon(getClass().getResource("/com/raven/image/Hamlet.jpeg")), "Unac"));
        home.addItem(new Model_Item("Giancarlo", "Sistemas", new ImageIcon(getClass().getResource("/com/raven/image/gianc.jpeg")), "Unac"));
          
    }
    
    private Point getLocationOf(Component com) {
        Point p = home.getPanelItemLocation();
        int x = p.x;
        int y = p.y;
        int itemX = com.getX();
        int itemY = com.getY();
        int left = 35;
        int top = 2;
        return new Point(x + itemX + left, y + itemY + top);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new com.raven.swing.MainPanel();

        mainPanel.setBackground(new java.awt.Color(238, 238, 238));
        mainPanel.setOpaque(true);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 813, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.swing.MainPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
